### PR TITLE
Correctly deserialize empty strings into empty sequence

### PR DESCRIPTION
**Pull request by d-e-s-o**
This change fixes the deserialization of a sequence (most likely
transformed into a Vec later) when an empty string is provided. So far
the result has been a sequence with a single empty string (or an error
when directly attempting to convert it further, say, into an integer).
It should be uncontroversial that an empty string (i.e., one without any
separator) represents an empty sequence and not a sequence with an
"empty" element.
To that end, this change adjusts the deserialization code to fix this
case.

Not sure if you consider this a breaking change or a bug fix. Up to you.
In any case, probably deserves a CHANGELOG entry such as:

> Fixed deserialization of empty string into sequence to no longer produce one element sequence

Closes: #50

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Can a new release please be published once this change has been merged?

**Comment by d-e-s-o** [comment]
So is this project to be considered abandoned? Can you please share what is going to happen with this repository, @softprops.

**Comment by softprops** [comment]
Apologies for that. I recently had an issue with all gh notification email getting caught by my email spam filter so I never got the original ping on this. 

 I have no intention of abdandoning this project since I use it ubiquitously.

**Comment by d-e-s-o** [comment]
Thanks for your response! I am glad to hear that. By any chance, could you cut a new release or provide any guidance on when a new one will be published?

**Comment by d-e-s-o** [comment]
Would you mind responding to the question posed above, @softprops?

**Comment by softprops** [comment]
I'll try to get to that this weekend

**Comment by softprops** [comment]
published in 0.4.2

**Comment by d-e-s-o** [comment]
> published in 0.4.2

Thank you!

**Pull request merged**
